Logger
Rinzii/Genesis pull request #2
Opened 2023-06-22 00:27 UTC by Kouros26

Pre-Graphical interface logger

2023-06-22 00:45 UTC, Rinzii requested changes
Left comments on suggestions for improvement. Everything is open for discussion of course. ^^

2023-06-22 00:45 UTC, Rinzii commented on editor/src/main.cpp
>  int main()
Remove this before we pull into the main branch. Could cause conflicts down the line if its not.

2023-06-22 00:45 UTC, Rinzii commented on engine/include/log.hpp
> +	public:
We are somewhat violating the singleton pattern by allowing our functions to be private. I'd think I'd benefit this code greatly to lock down what can access the logger. I'd start by making the constructor private to prevent the creation of additional instances of the logger.

2023-06-22 00:45 UTC, Rinzii commented on engine/include/log.hpp
> +	class Debug {
Give the class a more descriptive name than Debug. How about Logger?

2023-06-22 00:45 UTC, Rinzii commented on engine/include/log.hpp
> +		void Message(char const* message, char const* file, unsigned short line) const;
Use std::string instead of C style strings. Strings generally have much better safety and are more inline with modern C++.

2023-06-22 00:45 UTC, Rinzii commented on engine/src/log.cpp
> +void gen::Debug::Log(char const* message) const {
All of these functions can be put under a namespace instead of explicitly using the namespace directly.

2023-06-22 00:45 UTC, Rinzii commented on engine/include/log.hpp
> +
We need to delete the assignment and copy constructors to prevent the use of move and copy operations.

2023-06-22 00:45 UTC, Rinzii commented on engine/src/log.cpp
> +gen::Debug& gen::Debug::GetInstance() {
Generally with singletons its recommended to encapsulate the creation of the singleton instance withing a function to provide better control of initialization. I think we should instead create our singleton inside of a function like Initialize() or something.

2023-06-22 00:50 UTC, Rinzii requested changes

2023-06-22 00:50 UTC, Rinzii commented on engine/include/log.hpp
> +#define GEN_MSG(expression) gen::Debug::GetInstance().Message((expression), __FILE__, __LINE__)
Also consider using <source_location> instead of the C __FILE__ and __LINE__. We have access to C++20 so no reason to not use it.  :P

2023-06-22 01:24 UTC, Kouros26 commented on engine/include/log.hpp
> +	class Debug {
Yeah I chose Debug solely by thinking about Unity's Debug.Log but you're right Logger is better

2023-06-22 01:43 UTC, Kouros26 commented on engine/src/log.cpp
> +gen::Debug& gen::Debug::GetInstance() {
But then how do I access the instance in another function ?

2023-06-22 01:44 UTC, Kouros26 commented on engine/include/log.hpp
> +#define GEN_MSG(expression) gen::Debug::GetInstance().Message((expression), __FILE__, __LINE__)
Woops didn't know this was a thing

2023-06-22 01:47 UTC, Rinzii commented on engine/src/log.cpp
> +gen::Debug& gen::Debug::GetInstance() {
GetInstance() should return a reference to your instance and the instance itself should be stored as a member inside of the class on initialization.

2023-06-25 14:02 UTC, Rinzii approved these changes

2023-06-25 14:06 UTC, merged