Pch patch
Rinzii/genesis pull request #29
Opened 2023-07-16 10:46 UTC by Rinzii

closes #23

2023-07-16 15:55 UTC, karnkaul requested changes

2023-07-16 15:55 UTC, karnkaul commented on .github/workflows/build-nopch.yaml
Why are we using a different script? It adds a lot of redundant overhead of booting up the VMs, installing all the tools, configuring CMake, etc. I would recommend just modifying one of the stages (Debug or Release) in the existing build script to be passed `-DGENESIS_PCH=OFF`. We don't necessarily need multi-platform coverage either. (For faster CI turnaround times, since we rely on it to notify us of build errors in configurations we aren't building / developing on.)

2023-07-16 19:55 UTC, Rinzii commented on .github/workflows/build-nopch.yaml
I've added to it to now only run on vs22 and clang with no pch, but honestly we could also remove it from vs22 as it tends to be the slowest build time. Thoughts?

2023-07-17 06:24 UTC, karnkaul commented on .github/workflows/build-nopch.yaml
Sounds good!

2023-07-17 15:53 UTC, merged