Sync fileio
Rinzii/Genesis pull request #3
Opened 2023-06-28 15:56 UTC by Rinzii

This is only the sync fileio. I plan to implement async io at some point but this can get us started for the time being. I will note I've not really tested this code super extensively.

This PR is just to bring in sync io I'll keep the branch up though for async.

2023-06-28 16:13 UTC, Rinzii commented
Also a note to be made. This implementation kinda only handles binary files. I can add specializations for text files but in all honesty I don't think text files are going to be AS important till much later.

2023-06-28 19:42 UTC, Rinzii commented
Also added a bunch of useful stuff we will need later. Not really related to this PR or branch, but just gonna bunch em' together.

2023-06-30 17:06 UTC, Kouros26 requested changes

2023-06-30 17:06 UTC, Kouros26 commented on engine/src/io/file.cpp
you missed some consts on the ofstream, the streamsizes, the streampos and the filesystem functions

2023-06-30 18:30 UTC, Rinzii commented on engine/src/io/file.cpp
I should have got everything, but if you see anything else, lmk. ^^

2023-06-30 21:27 UTC, Kouros26 approved these changes

2023-06-30 21:27 UTC, merged

2023-06-30 21:29 UTC, Rinzii commented
async-fileio is still a WIP branch