Vulkan Window Surface Creation
Rinzii/genesis pull request #41
Opened 2023-08-09 20:49 UTC by Rinzii

2023-08-09 21:17 UTC, Kouros26 approved these changes

2023-08-09 21:49 UTC, karnkaul requested changes

2023-08-09 21:49 UTC, karnkaul commented on engine/src/graphics/device.cpp
> +		m_surface.release();
Why are we doing this manually though? Just having a default destructor and the correct member order will take care of it automatically. Kinda defeats the purpose of using RAII types.

2023-08-10 00:24 UTC, karnkaul requested changes
Note: vkUtils [still adds](https://github.com/Rinzii/genesis/blob/8e80e62698b3a5a39688e165e46cdac311f52807/engine/src/graphics/vkHelpers.cpp#L62) `VK_EXT_DEBUG_UTILS_EXTENSION_NAME` into the list of instance extensions.

2023-08-10 00:24 UTC, karnkaul commented on engine/src/graphics/device.cpp
>  		m_instance.release();
Now instance gets destroyed before surface 😄

2023-08-10 01:24 UTC, karnkaul approved these changes

2023-08-10 01:24 UTC, karnkaul commented on engine/include/graphics/device.hpp
> +		explicit GraphicsDevice(Window &window, std::string const & appName );
`window` can be `const&`, can't it?

2023-08-10 02:23 UTC, merged