Update log to add osyncstream and stream functionality along with better thread safety
Rinzii/Genesis pull request #7
Opened 2023-07-10 18:59 UTC by Rinzii

2023-07-10 20:41 UTC, Kouros26 commented
> Ok, I just learned AppleClang does not currently support C++20 osyncstream which is mega annoying. Should we say screw AppleClang and use normal Clang on macOS, or should I go through the trouble of manually implementing a custom version of osyncstream? Leaving AppleClang would make our support for iOS far more dubious but honestly as far as I can tell we don't really plan to support iOS. I can implement it, but it would be annoying. Personally, I think we should say screw AppleClang. What are your thoughts @Kouros26 ?

iOS support was never a priority for the engine so yeah, screw AppleClang

2023-07-11 21:04 UTC, Rinzii commented
I have decided that macOS is just not worth supporting with our project. Apple has gone so far out of its way to make life so much harder for developers that I don't have the desire to struggle to use C++20 on macOS. Especially because testing macOS with ci is actually painful requiring constant pushing to even see if the code works for them as Clang and AppleClang on MacOS don't work how clang works on Windows and Linux.

2023-07-12 01:01 UTC, Kouros26 requested changes

2023-07-12 06:25 UTC, Rinzii commented on engine/src/log.cpp
should be all clear now

2023-07-12 12:47 UTC, Kouros26 approved these changes

2023-07-12 12:47 UTC, merged